// WeatherApp-with-VueJS/src/components/Body.vue
<script setup>
import { ref } from 'vue';
import { getWeatherData } from "../dataProviders/weather";
import { createBodyData } from '../utils/createBodyData';

import CityInput from './partials/CityInput.vue';
import Loader from './partials/Loader.vue';
import NotFound from './partials/NotFound.vue';
import GeneralInfo from './partials/GeneralInfo.vue';
import InfoCard from './partials/InfoCard.vue';

const city = ref('');
const data = ref({});
const bodyData = ref([]);
const loading = ref(false);
const notFound = ref(false);
const inputChanges = ref(false);

const handleSearch = async (cityName) => {
  city.value = cityName;
  if (cityName == '') return;
  
  loading.value = true;
  notFound.value = false
  const weather = await getWeatherData(cityName);

  if (weather) {
    data.value = weather;
    bodyData.value = createBodyData(weather);
  } else {
    data.value = {};
    notFound.value = true;
  }

  loading.value = false;
  inputChanges.value = false;
};

const handleInputChange = () => {
  inputChanges.value = true;
}
</script>

<template>
<div class="">
  <div class="p-5 lg:p-10">
    <CityInput @search="handleSearch" @input="handleInputChange" />
    <Loader v-if="loading"/>
    <NotFound v-if="!loading && !inputChanges && notFound" :data="{city}"/>
    <div 
      v-if="!loading && !inputChanges && !notFound && Object.keys(data).length > 0" 
      class="text-center" role="status"
    >
      <div class="grid ">
        <GeneralInfo :data="data" :key="data.cod"/>
        <div class="grid grid-cols-2 gap-5 md:xl:2xl:grid-cols-3 place-content-center">
          <InfoCard v-for="data in bodyData" :data="data" :key="bodyData.indexOf(data)" />
        </div>
      </div>
    </div>
  </div>
</div>
</template>

<style scoped>
</style>

// WeatherApp-with-React/src/components/Body/Body.tsx
import { useEffect, useState } from "react";

import { useCityContext } from "../../contexts/CityContext";

import CityInput from "./Partials/CityInput/";
import GeneralInfo from "./Partials/GeneralInfo/";
import InfoCard from "./Partials/InfoCard/";
import Loader from "./Partials/Loader"
import NotFound from "./Partials/NotFound";

import IResponseData from "../../interfaces/IResponseData";
import IBodyData from "../../interfaces/IBodyData";

import { getWeatherData } from "../../dataProviders/weather";
import { createBodyData } from "../../utils/createBodyData";

const Body = (): JSX.Element => {
  const { city } = useCityContext();

  const [loading, setLoading] = useState(false);
  const [notFound, setNotFound] = useState(false);
  const [data, setData] = useState({} as IResponseData);
  const [infoCards, setInfoCards] = useState([] as JSX.Element[]);

  useEffect((): void => {
    const bodyData: IBodyData[] = createBodyData(data);
    const cards: JSX.Element[] = bodyData.map(data => <InfoCard data={data} key={bodyData.indexOf(data)}/>);
    setInfoCards(cards);
  }, [data]);

  useEffect((): void => {
    setNotFound(false);
    setData({} as IResponseData);
  }, [city])

  const handleSearch = async (): Promise<void> => {
    if (!city?.name) return;
    setLoading(true);
    const currentData: IResponseData | null = await getWeatherData(city?.name);
    if (currentData) {
      setData(currentData);
      setLoading(false);
      setNotFound(false);
    } else {
      setLoading(false);
      setNotFound(true);
    }
  };

  const weatherInfo: JSX.Element = (
    <>
      <div className="text-center" role="status">
        <div className="grid">
          <GeneralInfo data={data} />
          <div className="grid grid-cols-2 gap-5 md:xl:2xl:grid-cols-3 place-content-center">
            {infoCards}
          </div>
        </div>
      </div>
    </>
  )

  return (
    <div className="">
      <div className="p-5 lg:p-10">
        <CityInput  handleSearch={handleSearch}/>
        { loading ? <Loader/> : null }
        { !loading && notFound ? <NotFound/> : null }
        { 
          !loading && !notFound && Object.keys(data).length > 0 
            ? weatherInfo 
            : null
        }
      </div>
    </div>
  )
}

export default Body;
