// WeatherApp-with-Next/components/Body/Partials/CityInput/CityInput.tsx
import { MouseEventHandler, ReactElement } from 'react';
import { useCityContext } from '@/contexts/CityContext';

const CityInput = (props: {
  handleSearch: MouseEventHandler<HTMLButtonElement>
}): ReactElement => {
  const { city, setCity } = useCityContext();

  const handleChangeInput = (e: any): void => {
    setCity({ name: e.target.value });
  };

  return (
    <div className="h-56 flex flex-col items-center justify-center ">
      <div className="text-black grid gap-5">
        <input
          type="text"
          className="text-2xl bg-transparent outline-none border-b-2 w-96 h-12 pl-2 pr-2 capitalize"
          placeholder="Enter Your City Name"
          value={city?.name}
          onChange={handleChangeInput}
        />
        <button
          className="bn3 text-2xl"
          type="submit"
          onClick={props.handleSearch}
        >
          Search
        </button>
      </div>
    </div>
  )
}

export default CityInput;

// WeatherApp-with-VueJS/src/components/partials/CityInput.vue
<script setup>
import { ref } from 'vue';

const emit = defineEmits(['search', 'input']);
const city = ref('');

const handleChangeInput = (e) => {
  city.value = e.target.value;
  emit('input');
};

const handleClick = () => {
  const cityName = city.value;
  emit('search', cityName);
};
</script>

<template>
<div class="h-56 flex flex-col items-center justify-center ">
  <div class="text-black grid gap-5">
    <input
      type="text"
      class="text-2xl bg-transparent outline-none border-b-2 w-96 h-12 pl-2 pr-2 capitalize"
      placeholder="Enter Your City"
      @value=city.value
      @input="handleChangeInput"
    />
    <button class="bn3" type="submit" @click="handleClick">
      Search
    </button>
  </div>
</div>
</template>

<style scoped>
</style>
