// WeatherApp-with-Next/components/Body/Partials/InfoCard/InfoCard.tsx
import { ReactElement } from 'react';
import IBodyData from '@/interfaces/IBodyData';

const InfoCard = (props: {
  data: IBodyData
}): ReactElement => {

  return (
    <div className="border-2 rounded-lg p-2">
      <h3 className="flex text-center items-center justify-center gap-2 rounded-lg text-2xl">
        <props.data.icon size={30} />
        {props.data.text + ': '}
        {props.data.value}{props.data.units}
      </h3>
    </div>
  )
}

export default InfoCard;

// WeatherApp-with-VueJS/src/components/partials/InfoCard.vue
<script setup>
const props = defineProps({
  data: {
    type: Object,
    required: true,
    default: () => ({
      icon: string,
      value: number,
      units: string,
      text: string
    })
  }
})
</script>

<template>
<div class="border-2 rounded-lg p-2">
  <h3 class="flex text-center items-center justify-center gap-2 rounded-lg text-2xl">
    <i :class="props.data.icon"></i>
    {{props.data.text + ': '}}
    {{props.data.value + '' + props.data.units}}
  </h3>
</div>
</template>

<style scoped>
</style>
