// WeatherApp-with-Next/app/page.tsx
'use server'
import logo from '../public/logo.gif';
import { sourceCodeUrl, dataProviderUrl, nextUrl } from '@/constants/appConstants';
import { CityContextProvider } from '@/contexts/CityContext';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ErrorBoundary from '@/components/ErrorBoundary';

export default async function Home() {

  return (
    <div id="root">
      <ErrorBoundary>
        <CityContextProvider>
          <Header logo={logo} nextUrl={nextUrl} />
          
          <Footer sourceCode={sourceCodeUrl} dataProviderUrl={dataProviderUrl} />
        </CityContextProvider>
      </ErrorBoundary>
    </div>
  );
}

// WeatherApp-with-VueJS/src/App.vue
<script setup>
import { 
  logo, 
  vueJSUrl, 
  dataProviderUrl, 
  sourceCodeUrl 
} from "./constants/appConstants";

import Header from './components/Header.vue';
import Footer from './components/Footer.vue';
</script>

<template>
  <Header :data="{logo, vueJSUrl}"/>
  <Footer :data="{dataProviderUrl, sourceCodeUrl}"/>
</template>

<style scoped>
</style>
