// WeatherApp-with-React/src/App.tsx
import "./assets/css/styles.css";

import logo from "./assets/img/logo.gif";
import { sourceCodeUrl, dataProviderUrl, reactTSUrl } from "./constants/appConstants";

import ErrorBoundary from "./components/ErrorBoundary/";
import Header from "./components/Header";
import Footer from "./components/Footer";

function App(): JSX.Element {

  return (
    <ErrorBoundary>
      <Header logo={logo} reactTSUrl={reactTSUrl} />
      <Footer sourceCode={sourceCodeUrl} dataProviderUrl={dataProviderUrl} />
    </ErrorBoundary>
  );
}

export default App;

// WeatherApp-with-VueJS/src/App.vue
<script setup>
import { 
  logo, 
  vueJSUrl, 
  dataProviderUrl, 
  sourceCodeUrl 
} from "./constants/appConstants";

import Header from './components/Header.vue';
import Footer from './components/Footer.vue';
</script>

<template>
  <Header :data="{logo, vueJSUrl}"/>
  <Footer :data="{dataProviderUrl, sourceCodeUrl}"/>
</template>

<style scoped>
</style>
