// WeatherApp-with-Next/components/Footer/Footer.tsx
import Link from 'next/link';
import { ReactElement } from 'react';

import './Footer.css';

const Footer = (props: {
  sourceCode: string,
  dataProviderUrl: string
}): ReactElement => {
  return (
    <>
      <hr className='hr-bottom' />
      <Link
        href={props.dataProviderUrl}
        target={"_blank"}
        rel="noreferrer"
        className="text-3xl font-semibold absolute bottom-5 left-10"
      >
        Data Provider
      </Link>
      <Link
        href={props.sourceCode}
        target={"_blank"}
        rel="noreferrer"
        className="text-3xl font-semibold absolute bottom-5 right-10"
      >
        Source Code
      </Link>
    </>
  )
}

export default Footer;

// WeatherApp-with-VueJS/src/components/Footer.vue
<script setup>
const props = defineProps({
  data: {
    type: Object,
    required: true,
    default: () => ({
      dataProviderUrl: string,
      sourceCodeUrl: string
    })
  }
});
</script>

<template>
  <hr class='hr-bottom' />
  <a 
    :href=props.data.dataProviderUrl 
    target="_blank" 
    rel="noreferrer"
    class="text-3xl font-semibold absolute bottom-5 left-10">
    Data Provider
  </a>
  <a 
    :href=props.data.sourceCodeUrl 
    target="_blank" 
    rel="noreferrer"
    class="text-3xl font-semibold absolute bottom-5 right-10">
    Source Code
  </a>
</template>

<style scoped>
</style>
