// WeatherApp-with-Next/components/Header/Header.tsx
import Link from 'next/link';
import Image, { StaticImageData } from 'next/image';
import { ReactElement } from 'react';
import { FiMoon, FiSun } from 'react-icons/fi';
import ToggleTheme from './Partials/ToggleTheme';

import './Header.css';

const Header = (props: {
  logo: StaticImageData,
  nextUrl: string
}): ReactElement => {
  return (
    <>
      <Link
        href={props.nextUrl}
        target={"_blank"}
        rel="noreferrer"
        className="text-3xl flex items-center gap-2 absolute top-2 left-10 font-semibold"
      >
        <Image src={props.logo} className="w-[120px]" id="logo" alt="logo" />
        Weather App with NEXT.JS
      </Link>
      <div className="icon-button toggle-theme">
        <ToggleTheme />
        <label
          htmlFor="checkbox"
          className="label top-2 right-10"
        >
          <FiMoon color="white" />
          <FiSun color="yellow" />
          <div className="ball"></div>
        </label>
      </div>
      <hr className='hr-top' />
    </>
  )
}

export default Header;

// WeatherApp-with-VueJS/src/components/Header.vue
<script setup>
import { onMounted } from "vue";

onMounted(() => {document.body.classList.add('light')});

const props = defineProps({
  data: {
    type: Object,
    required: true,
    default: () => ({
      logo: string,
      vueJSUrl: string
    })
  }
});

const toggleTheme = () => {
  // to implement
};
</script>

<template>
  <a
    :href=props.data.vueJSUrl
    target="_blank"
    rel="noreferrer"
    class="text-3xl flex items-center gap-2 absolute top-2 left-10 font-semibold"
  >
    <img :src=props.data.logo class="w-[120px]" id="logo" alt="logo" />
    Weather App with Vue.JS
  </a>
  <div class="icon-button toggle-theme">
    <input
      type="checkbox"
      class="checkbox"
      id="checkbox"
      @click=toggleTheme
    />
    <label
      for="checkbox"
      class="label top-2 right-10"
    >
      <i class="fa-regular fa-sun" style="color: white;"></i>
      <i class="fa-regular fa-moon" style="color: yellow;"></i>
      <div class="ball"></div>
    </label>
  </div>
  <hr class='hr-top' />
</template>

<style scoped>
</style>
