// WeatherApp-with-VueJS/src/components/Body.vue
<script setup>
import { ref } from 'vue';
import { getWeatherData } from "../dataProviders/weather";
import { createBodyData } from '../utils/createBodyData';

import CityInput from './partials/CityInput.vue';
import Loader from './partials/Loader.vue';
import NotFound from './partials/NotFound.vue';
import GeneralInfo from './partials/GeneralInfo.vue';
import InfoCard from './partials/InfoCard.vue';

const city = ref('');
const data = ref({});
const bodyData = ref([]);
const loading = ref(false);
const notFound = ref(false);
const inputChanges = ref(false);

const handleSearch = async (cityName) => {
  city.value = cityName;
  if (cityName == '') return;
  
  loading.value = true;
  notFound.value = false
  const weather = await getWeatherData(cityName);

  if (weather) {
    data.value = weather;
    bodyData.value = createBodyData(weather);
  } else {
    data.value = {};
    notFound.value = true;
  }

  loading.value = false;
  inputChanges.value = false;
};

const handleInputChange = () => {
  inputChanges.value = true;
}
</script>

<template>
<div class="">
  <div class="p-5 lg:p-10">
    <CityInput @search="handleSearch" @input="handleInputChange" />
    <Loader v-if="loading"/>
    <NotFound v-if="!loading && !inputChanges && notFound" :data="{city}"/>
    <div 
      v-if="!loading && !inputChanges && !notFound && Object.keys(data).length > 0" 
      class="text-center" role="status"
    >
      <div class="grid ">
        <GeneralInfo :data="data" :key="data.cod"/>
        <div class="grid grid-cols-2 gap-5 md:xl:2xl:grid-cols-3 place-content-center">
          <InfoCard v-for="data in bodyData" :data="data" :key="bodyData.indexOf(data)" />
        </div>
      </div>
    </div>
  </div>
</div>
</template>

<style scoped>
</style>

// WeatherApp-with-Next/components/Body/Body.tsx
'use client'
import { usePathname, useRouter, useSearchParams } from 'next/navigation';

import { ReactElement, useEffect, useState, useTransition } from 'react';
import { useCityContext } from '@/contexts/CityContext';

import CityInput from './Partials/CityInput/';
import GeneralInfo from './Partials/GeneralInfo/';
import InfoCard from './Partials/InfoCard/';
import Loader from './Partials/Loader/';

import IResponseData from '@/interfaces/IResponseData';
import IBodyData from '@/interfaces/IBodyData';

import { createBodyData } from '@/utils/createBodyData';

const Body = (props: {
  data: IResponseData,
}): ReactElement => {
  const { city } = useCityContext();

  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();

  const [isPending, startTransition] = useTransition();
  const [inputChanges, setInputChanges] = useState(false);
  const [notFound, setNotFound] = useState(false);
  const [infoCards, setInfoCards] = useState([] as ReactElement[]);

  useEffect((): void => {
    if (Object.keys(props.data).length == 0) {
      setNotFound(true);
    } else {
      setNotFound(false);
    }

    const bodyData: IBodyData[] = createBodyData(props.data);
    const cards: ReactElement[] = bodyData.map(data => <InfoCard data={data} key={bodyData.indexOf(data)}/>);
    setInfoCards(cards);
  }, [props.data]);

  useEffect((): void => {
    setInputChanges(true);
  }, [city]);

  const handleSearch = async (): Promise<void> => {
    if (!city.name) return;

    setNotFound(true);
    setInputChanges(false);

    const updatedSearchParams = new URLSearchParams(searchParams);
    updatedSearchParams.set("city", city.name);

    startTransition(() => {
      router.replace(`${pathname}?${updatedSearchParams.toString()}`);
    });
  };

  const weatherInfo: ReactElement = (
    <>
      <div className="text-center" role="status">
        <div className="grid">
          <GeneralInfo data={props.data} />
          <div className="grid grid-cols-2 gap-5 md:xl:2xl:grid-cols-3 place-content-center">
            {infoCards}
          </div>
        </div>
      </div>
    </>
  )

  return (
    <div className="">
      <div className="p-5 lg:p-10">
        <h2>Weather Data</h2>
      </div>
    </div>
  )
}

export default Body;
