// WeatherApp-with-Angular/src/app/core/footer/footer.component.ts
import { Component } from '@angular/core';
import { dataProviderUrl, sourceCodeUrl } from '../../shared/constants/appConstants'

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css'],
})
export class FooterComponent {
  dataProviderUrl: string;
  sourceCodeUrl: string;

  constructor() {
    this.dataProviderUrl = dataProviderUrl;
    this.sourceCodeUrl = sourceCodeUrl;
  }
}

<hr class='hr-bottom' />
<a 
  href="{{dataProviderUrl}}"
  target="_blank" 
  rel="noreferrer"
  class="text-3xl font-semibold absolute bottom-5 left-10">
  Data Provider
</a>
<a 
  href="{{sourceCodeUrl}}" 
  target="_blank" 
  rel="noreferrer"
  class="text-3xl font-semibold absolute bottom-5 right-10">
  Source Code
</a>

// WeatherApp-with-React/src/components/Footer/Footer.tsx
import './Footer.css';

const Footer = (props: {
  sourceCode: string,
  dataProviderUrl: string
}): JSX.Element => {
  return (
    <>
      <hr className='hr-bottom' />
      <a
        href={props.dataProviderUrl}
        target={"_blank"}
        rel="noreferrer"
        className="text-3xl font-semibold absolute bottom-5 left-10"
      >
        Data Provider
      </a>
      <a
        href={props.sourceCode}
        target={"_blank"}
        rel="noreferrer"
        className="text-3xl font-semibold absolute bottom-5 right-10"
      >
        Source Code
      </a>
    </>
  )
}

export default Footer;
