// WeatherApp-with-VueJS/src/components/Header.vue
<script setup>
import { onMounted } from "vue";

onMounted(() => {document.body.classList.add('light')});

const props = defineProps({
  data: {
    type: Object,
    required: true,
    default: () => ({
      logo: string,
      vueJSUrl: string
    })
  }
});

const toggleTheme = () => {
  // to implement
};
</script>

<template>
  <a
    :href=props.data.vueJSUrl
    target="_blank"
    rel="noreferrer"
    class="text-3xl flex items-center gap-2 absolute top-2 left-10 font-semibold"
  >
    <img :src=props.data.logo class="w-[120px]" id="logo" alt="logo" />
    Weather App with Vue.JS
  </a>
  <div class="icon-button toggle-theme">
    <input
      type="checkbox"
      class="checkbox"
      id="checkbox"
      @click=toggleTheme
    />
    <label
      for="checkbox"
      class="label top-2 right-10"
    >
      <i class="fa-regular fa-sun" style="color: white;"></i>
      <i class="fa-regular fa-moon" style="color: yellow;"></i>
      <div class="ball"></div>
    </label>
  </div>
  <hr class='hr-top' />
</template>

<style scoped>
</style>

// WeatherApp-with-React/src/components/Header/Header.tsx
import './Header.css';

import Theme from '../../enumerations/theme';

import { useEffect, useState } from 'react';
import { FiMoon, FiSun } from 'react-icons/fi';

const Header = (props: {
  logo: string,
  reactTSUrl: string
}): JSX.Element => {
  const [theme, setTheme] = useState(Theme[0]);

  const toggleTheme = (): void => {
    // to implement ...
  };

  useEffect((): void => {
    document.body.className = theme;
  }, [theme]);

  return (
    <>
      <a
        href={props.reactTSUrl}
        target={"_blank"}
        rel="noreferrer"
        className="text-3xl flex items-center gap-2 absolute top-2 left-10 font-semibold"
      >
        <img src={props.logo} className="w-[120px]" id="logo" alt="logo" />
        Weather App with React.TS
      </a>
      <div className="icon-button toggle-theme">
        <input
          type="checkbox"
          className="checkbox"
          id="checkbox"
          onClick={toggleTheme}
        />
        <label
          htmlFor="checkbox"
          className="label top-2 right-10"
        >
          <FiMoon color="white" />
          <FiSun color="yellow" />
          <div className="ball"></div>
        </label>
      </div>
      <hr className='hr-top' />
    </>
  )
}

export default Header;
